{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import os\n",
    "import sys\n",
    "sys.path.append(r'C:\\Users\\Max Tost\\Desktop\\Notebooks\\SPC Neural Network Project')\n",
    "from sklearn.datasets import load_iris\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score\n",
    "import xgboost as xgb\n",
    "import matplotlib.pyplot as plt # for plotting\n",
    "import seaborn as sns # for plotting\n",
    "import pandas as pd # for data manipulation\n",
    "from Models.load_data import *\n",
    "\n",
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load the Iris dataset\n",
    "iris = load_iris()\n",
    "X = iris.data  # Features\n",
    "y = iris.target  # Labels\n",
    "\n",
    "# Split the dataset into training and testing sets\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Key ECE_PF not in JETno100176.csv. Filling it with zeros.\n",
      "Key RNT not in JETno100184.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno100198.csv. Filling it with zeros.\n",
      "Key RNT not in JETno100228.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno100535.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno80609.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno80848.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno80853.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno81187.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno81568.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno81586.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno81929.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno82017.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno82257.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno82466.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno82811.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno82826.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno82874.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno82874.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno82963.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno83143.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno83235.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno83611.csv. Filling it with zeros.\n",
      "Key RNT not in JETno83619.csv. Filling it with zeros.\n",
      "Key RNT not in JETno84142.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno84142.csv. Filling it with zeros.\n",
      "Key RNT not in JETno84165.csv. Filling it with zeros.\n",
      "Key DAO_EDG7 not in JETno85548.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno85548.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno85548.csv. Filling it with zeros.\n",
      "Key RNT not in JETno85605.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno85824.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno86337.csv. Filling it with zeros.\n",
      "Key RNT not in JETno86670.csv. Filling it with zeros.\n",
      "Key RNT not in JETno89081.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno89214.csv. Filling it with zeros.\n",
      "Key RNT not in JETno89317.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno89421.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno89439.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno89744.csv. Filling it with zeros.\n",
      "Key RNT not in JETno89795.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno90644.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno91888.csv. Filling it with zeros.\n",
      "Key RNT not in JETno94219.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno94357.csv. Filling it with zeros.\n",
      "Key RNT not in JETno94450.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno94496.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno94507.csv. Filling it with zeros.\n",
      "Key RNT not in JETno94586.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno94633.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno94680.csv. Filling it with zeros.\n",
      "Key RNT not in JETno95072.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno95136.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno95205.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno95360.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno95867.csv. Filling it with zeros.\n",
      "Key IPLA not in JETno95927.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno95986.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno96002.csv. Filling it with zeros.\n",
      "Key RNT not in JETno96912.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno97441.csv. Filling it with zeros.\n",
      "Key RNT not in JETno97561.csv. Filling it with zeros.\n",
      "Key DAO_EDG7 not in JETno97683.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno97683.csv. Filling it with zeros.\n",
      "Key RNT not in JETno97986.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno98083.csv. Filling it with zeros.\n",
      "Key RNT not in JETno98938.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno98982.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno99010.csv. Filling it with zeros.\n",
      "Key RNT not in JETno99134.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno99138.csv. Filling it with zeros.\n",
      "Key DAO_EDG7 not in JETno99243.csv. Filling it with zeros.\n",
      "Key DAI_EDG7 not in JETno99243.csv. Filling it with zeros.\n",
      "Key ECE_PF not in JETno99275.csv. Filling it with zeros.\n",
      "Key RNT not in JETno99738.csv. Filling it with zeros.\n",
      "Key RNT not in JETno99751.csv. Filling it with zeros.\n",
      "Key RNT not in JETno99776.csv. Filling it with zeros.\n",
      "Key RNT not in JETno99868.csv. Filling it with zeros.\n",
      "Combined features shape: (1800004, 6)\n",
      "Combined targets shape: (1800004,)\n"
     ]
    }
   ],
   "source": [
    "path = r'C:\\Users\\Max Tost\\Desktop\\Notebooks\\SPC Neural Network Project\\Training_data'\n",
    "features_list = os.listdir(os.path.join(path, r'features'))\n",
    "\n",
    "# Replace 'path' and 'features_list' with your actual base path and list of feature file names.\n",
    "X, y = load_all_data(path, features_list)\n",
    "\n",
    "print(\"Combined features shape:\", X.shape)\n",
    "print(\"Combined targets shape:\", y.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "features_sequence = ['SSXcore', 'IPLA', 'DAO_EDG7', 'RNT', 'DAI_EDG7', 'ECE_PF']\n",
    "\n",
    "data = pd.DataFrame(X, columns=features_sequence)\n",
    "data['label']=y\n",
    "data['label'] = data['label'].map({0: 'No RE', 1: 'RE'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[89], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m sns\u001b[38;5;241m.\u001b[39mpairplot(data, hue\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mlabel\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m      2\u001b[0m plt\u001b[38;5;241m.\u001b[39mshow()\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\seaborn\\axisgrid.py:2158\u001b[0m, in \u001b[0;36mpairplot\u001b[1;34m(data, hue, hue_order, palette, vars, x_vars, y_vars, kind, diag_kind, markers, height, aspect, corner, dropna, plot_kws, diag_kws, grid_kws, size)\u001b[0m\n\u001b[0;32m   2156\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m kind \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mscatter\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[0;32m   2157\u001b[0m     \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mrelational\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m scatterplot  \u001b[38;5;66;03m# Avoid circular import\u001b[39;00m\n\u001b[1;32m-> 2158\u001b[0m     plotter(scatterplot, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mplot_kws)\n\u001b[0;32m   2159\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m kind \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mreg\u001b[39m\u001b[38;5;124m\"\u001b[39m:\n\u001b[0;32m   2160\u001b[0m     \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mregression\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m regplot  \u001b[38;5;66;03m# Avoid circular import\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\seaborn\\axisgrid.py:1419\u001b[0m, in \u001b[0;36mPairGrid.map_offdiag\u001b[1;34m(self, func, **kwargs)\u001b[0m\n\u001b[0;32m   1408\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"Plot with a bivariate function on the off-diagonal subplots.\u001b[39;00m\n\u001b[0;32m   1409\u001b[0m \n\u001b[0;32m   1410\u001b[0m \u001b[38;5;124;03mParameters\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1416\u001b[0m \n\u001b[0;32m   1417\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m   1418\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msquare_grid:\n\u001b[1;32m-> 1419\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmap_lower(func, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m   1420\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_corner:\n\u001b[0;32m   1421\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmap_upper(func, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\seaborn\\axisgrid.py:1389\u001b[0m, in \u001b[0;36mPairGrid.map_lower\u001b[1;34m(self, func, **kwargs)\u001b[0m\n\u001b[0;32m   1378\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"Plot with a bivariate function on the lower diagonal subplots.\u001b[39;00m\n\u001b[0;32m   1379\u001b[0m \n\u001b[0;32m   1380\u001b[0m \u001b[38;5;124;03mParameters\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1386\u001b[0m \n\u001b[0;32m   1387\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m   1388\u001b[0m indices \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mzip\u001b[39m(\u001b[38;5;241m*\u001b[39mnp\u001b[38;5;241m.\u001b[39mtril_indices_from(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39maxes, \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m))\n\u001b[1;32m-> 1389\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_map_bivariate(func, indices, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m   1390\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\seaborn\\axisgrid.py:1568\u001b[0m, in \u001b[0;36mPairGrid._map_bivariate\u001b[1;34m(self, func, indices, **kwargs)\u001b[0m\n\u001b[0;32m   1566\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m ax \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:  \u001b[38;5;66;03m# i.e. we are in corner mode\u001b[39;00m\n\u001b[0;32m   1567\u001b[0m         \u001b[38;5;28;01mcontinue\u001b[39;00m\n\u001b[1;32m-> 1568\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_plot_bivariate(x_var, y_var, ax, func, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkws)\n\u001b[0;32m   1569\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_add_axis_labels()\n\u001b[0;32m   1571\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhue\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m signature(func)\u001b[38;5;241m.\u001b[39mparameters:\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\seaborn\\axisgrid.py:1609\u001b[0m, in \u001b[0;36mPairGrid._plot_bivariate\u001b[1;34m(self, x_var, y_var, ax, func, **kwargs)\u001b[0m\n\u001b[0;32m   1605\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhue\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;129;01min\u001b[39;00m kwargs:\n\u001b[0;32m   1606\u001b[0m     kwargs\u001b[38;5;241m.\u001b[39mupdate({\n\u001b[0;32m   1607\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhue\u001b[39m\u001b[38;5;124m\"\u001b[39m: hue, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhue_order\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_hue_order, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mpalette\u001b[39m\u001b[38;5;124m\"\u001b[39m: \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_orig_palette,\n\u001b[0;32m   1608\u001b[0m     })\n\u001b[1;32m-> 1609\u001b[0m func(x\u001b[38;5;241m=\u001b[39mx, y\u001b[38;5;241m=\u001b[39my, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m   1611\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_update_legend_data(ax)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\seaborn\\relational.py:761\u001b[0m, in \u001b[0;36mscatterplot\u001b[1;34m(data, x, y, hue, size, style, palette, hue_order, hue_norm, sizes, size_order, size_norm, markers, style_order, legend, ax, **kwargs)\u001b[0m\n\u001b[0;32m    758\u001b[0m color \u001b[38;5;241m=\u001b[39m kwargs\u001b[38;5;241m.\u001b[39mpop(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcolor\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[0;32m    759\u001b[0m kwargs[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcolor\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m _default_color(ax\u001b[38;5;241m.\u001b[39mscatter, hue, color, kwargs)\n\u001b[1;32m--> 761\u001b[0m p\u001b[38;5;241m.\u001b[39mplot(ax, kwargs)\n\u001b[0;32m    763\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m ax\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\seaborn\\relational.py:578\u001b[0m, in \u001b[0;36m_ScatterPlotter.plot\u001b[1;34m(self, ax, kws)\u001b[0m\n\u001b[0;32m    575\u001b[0m \u001b[38;5;66;03m# Apply the mapping from semantic variables to artist attributes\u001b[39;00m\n\u001b[0;32m    577\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhue\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mvariables:\n\u001b[1;32m--> 578\u001b[0m     points\u001b[38;5;241m.\u001b[39mset_facecolors(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_hue_map(data[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhue\u001b[39m\u001b[38;5;124m\"\u001b[39m]))\n\u001b[0;32m    580\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msize\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mvariables:\n\u001b[0;32m    581\u001b[0m     points\u001b[38;5;241m.\u001b[39mset_sizes(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_size_map(data[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msize\u001b[39m\u001b[38;5;124m\"\u001b[39m]))\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\matplotlib\\_api\\__init__.py:256\u001b[0m, in \u001b[0;36mdefine_aliases.<locals>.make_alias.<locals>.method\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    254\u001b[0m \u001b[38;5;129m@functools\u001b[39m\u001b[38;5;241m.\u001b[39mwraps(\u001b[38;5;28mgetattr\u001b[39m(\u001b[38;5;28mcls\u001b[39m, name))\n\u001b[0;32m    255\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mmethod\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m--> 256\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mgetattr\u001b[39m(\u001b[38;5;28mself\u001b[39m, name)(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\matplotlib\\collections.py:751\u001b[0m, in \u001b[0;36mCollection.set_facecolor\u001b[1;34m(self, c)\u001b[0m\n\u001b[0;32m    749\u001b[0m     c \u001b[38;5;241m=\u001b[39m c\u001b[38;5;241m.\u001b[39mlower()\n\u001b[0;32m    750\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_original_facecolor \u001b[38;5;241m=\u001b[39m c\n\u001b[1;32m--> 751\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_set_facecolor(c)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\matplotlib\\collections.py:733\u001b[0m, in \u001b[0;36mCollection._set_facecolor\u001b[1;34m(self, c)\u001b[0m\n\u001b[0;32m    730\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m c \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    731\u001b[0m     c \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_get_default_facecolor()\n\u001b[1;32m--> 733\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_facecolors \u001b[38;5;241m=\u001b[39m mcolors\u001b[38;5;241m.\u001b[39mto_rgba_array(c, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_alpha)\n\u001b[0;32m    734\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mstale \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\matplotlib\\colors.py:481\u001b[0m, in \u001b[0;36mto_rgba_array\u001b[1;34m(c, alpha)\u001b[0m\n\u001b[0;32m    479\u001b[0m lens \u001b[38;5;241m=\u001b[39m {\u001b[38;5;28mlen\u001b[39m(cc) \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(cc, (\u001b[38;5;28mlist\u001b[39m, \u001b[38;5;28mtuple\u001b[39m)) \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m1\u001b[39m \u001b[38;5;28;01mfor\u001b[39;00m cc \u001b[38;5;129;01min\u001b[39;00m c}\n\u001b[0;32m    480\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m lens \u001b[38;5;241m==\u001b[39m {\u001b[38;5;241m3\u001b[39m}:\n\u001b[1;32m--> 481\u001b[0m     rgba \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39mcolumn_stack([c, np\u001b[38;5;241m.\u001b[39mones(\u001b[38;5;28mlen\u001b[39m(c))])\n\u001b[0;32m    482\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m lens \u001b[38;5;241m==\u001b[39m {\u001b[38;5;241m4\u001b[39m}:\n\u001b[0;32m    483\u001b[0m     rgba \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39marray(c)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\numpy\\lib\\shape_base.py:651\u001b[0m, in \u001b[0;36mcolumn_stack\u001b[1;34m(tup)\u001b[0m\n\u001b[0;32m    649\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m arr\u001b[38;5;241m.\u001b[39mndim \u001b[38;5;241m<\u001b[39m \u001b[38;5;241m2\u001b[39m:\n\u001b[0;32m    650\u001b[0m         arr \u001b[38;5;241m=\u001b[39m array(arr, copy\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m, subok\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m, ndmin\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m2\u001b[39m)\u001b[38;5;241m.\u001b[39mT\n\u001b[1;32m--> 651\u001b[0m     arrays\u001b[38;5;241m.\u001b[39mappend(arr)\n\u001b[0;32m    652\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m _nx\u001b[38;5;241m.\u001b[39mconcatenate(arrays, \u001b[38;5;241m1\u001b[39m)\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error in callback <function _draw_all_if_interactive at 0x0000020BA0E57880> (for post_execute):\n"
     ]
    }
   ],
   "source": [
    "sns.pairplot(data, hue='label')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of threadpoolctl failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 349, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 309, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 0 free vars, not 2946347565057\n",
      "]\n",
      "[autoreload of sklearn.utils.fixes failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py\", line 25, in <module>\n",
      "    from .parallel import _get_threadpool_controller\n",
      "ImportError: cannot import name '_get_threadpool_controller' from 'sklearn.utils.parallel' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\parallel.py)\n",
      "]\n",
      "[autoreload of sklearn.utils.validation failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 23, in <module>\n",
      "    from ..utils.fixes import ComplexWarning, _preserve_dia_indices_dtype\n",
      "ImportError: cannot import name 'ComplexWarning' from 'sklearn.utils.fixes' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.utils.class_weight failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 309, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: compute_class_weight() requires a code object with 0 free vars, not 2946347565059\n",
      "]\n",
      "[autoreload of sklearn.utils failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\__init__.py\", line 23, in <module>\n",
      "    from ._indexing import (\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_indexing.py\", line 15, in <module>\n",
      "    from .extmath import _approximate_mode\n",
      "ImportError: cannot import name '_approximate_mode' from 'sklearn.utils.extmath' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\extmath.py)\n",
      "]\n",
      "[autoreload of sklearn.utils._set_output failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_set_output.py\", line 13, in <module>\n",
      "    from .fixes import _create_pandas_dataframe_from_non_pandas_container\n",
      "ImportError: cannot import name '_create_pandas_dataframe_from_non_pandas_container' from 'sklearn.utils.fixes' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.utils._tags failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_tags.py\", line 8, in <module>\n",
      "    from .fixes import _dataclass_args\n",
      "ImportError: cannot import name '_dataclass_args' from 'sklearn.utils.fixes' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\base.py\", line 23, in <module>\n",
      "    from .utils._tags import (\n",
      "ImportError: cannot import name 'ClassifierTags' from 'sklearn.utils._tags' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_tags.py)\n",
      "]\n",
      "[autoreload of sklearn.utils.extmath failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 309, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: randomized_svd() requires a code object with 0 free vars, not 2946347565059\n",
      "]\n",
      "[autoreload of sklearn.utils.sparsefuncs failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\sparsefuncs.py\", line 10, in <module>\n",
      "    from ..utils.fixes import _sparse_min_max, _sparse_nan_min_max\n",
      "ImportError: cannot import name '_sparse_min_max' from 'sklearn.utils.fixes' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._encoders failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\preprocessing\\_encoders.py\", line 18, in <module>\n",
      "    from ..utils.validation import (\n",
      "ImportError: cannot import name '_check_feature_names' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._data failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\preprocessing\\_data.py\", line 35, in <module>\n",
      "    from ..utils.validation import (\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._discretization failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\preprocessing\\_discretization.py\", line 15, in <module>\n",
      "    from ..utils.validation import (\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.utils.metaestimators failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\metaestimators.py\", line 14, in <module>\n",
      "    from ..utils._tags import get_tags\n",
      "ImportError: cannot import name 'get_tags' from 'sklearn.utils._tags' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_tags.py)\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._function_transformer failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\preprocessing\\_function_transformer.py\", line 12, in <module>\n",
      "    from ..utils._set_output import (\n",
      "ImportError: cannot import name '_get_adapter_from_container' from 'sklearn.utils._set_output' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_set_output.py)\n",
      "]\n",
      "[autoreload of sklearn.utils.multiclass failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\multiclass.py\", line 14, in <module>\n",
      "    from ..utils.fixes import VisibleDeprecationWarning\n",
      "ImportError: cannot import name 'VisibleDeprecationWarning' from 'sklearn.utils.fixes' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._label failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 349, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 309, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: fit_transform() requires a code object with 2 free vars, not 2946347565056\n",
      "]\n",
      "[autoreload of sklearn.preprocessing._polynomial failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\preprocessing\\_polynomial.py\", line 23, in <module>\n",
      "    from ..utils.validation import (\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.datasets._lfw failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\datasets\\_lfw.py\", line 22, in <module>\n",
      "    from ..utils.fixes import tarfile_extractall\n",
      "ImportError: cannot import name 'tarfile_extractall' from 'sklearn.utils.fixes' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.datasets._arff_parser failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\datasets\\_arff_parser.py\", line 19, in <module>\n",
      "    from ..utils.fixes import pd_fillna\n",
      "ImportError: cannot import name 'pd_fillna' from 'sklearn.utils.fixes' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.datasets._openml failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 309, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: fetch_openml() requires a code object with 0 free vars, not 2946347565059\n",
      "]\n",
      "[autoreload of sklearn.feature_extraction.text failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\feature_extraction\\text.py\", line 25, in <module>\n",
      "    from ..utils.fixes import _IS_32BIT\n",
      "ImportError: cannot import name '_IS_32BIT' from 'sklearn.utils.fixes' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.feature_extraction.image failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\feature_extraction\\image.py\", line 25, in <module>\n",
      "    from ..utils.validation import validate_data\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.datasets._twenty_newsgroups failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\datasets\\_twenty_newsgroups.py\", line 46, in <module>\n",
      "    from ..utils.fixes import tarfile_extractall\n",
      "ImportError: cannot import name 'tarfile_extractall' from 'sklearn.utils.fixes' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py)\n",
      "]\n",
      "[autoreload of sklearn.metrics.cluster._bicluster failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 309, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: consensus_score() requires a code object with 0 free vars, not 2946347565059\n",
      "]\n",
      "[autoreload of sklearn.metrics.pairwise failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 309, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: euclidean_distances() requires a code object with 0 free vars, not 2946347565059\n",
      "]\n",
      "[autoreload of sklearn.metrics._scorer failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 44, in <module>\n",
      "    from . import (\n",
      "ImportError: cannot import name 'root_mean_squared_error' from 'sklearn.metrics' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\metrics\\__init__.py)\n",
      "]\n",
      "[autoreload of sklearn.model_selection._validation failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 45, in <module>\n",
      "    from ..utils.validation import _check_method_params, _num_samples\n",
      "ImportError: cannot import name '_check_method_params' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.model_selection._search failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\model_selection\\_search.py\", line 35, in <module>\n",
      "    from ..utils._tags import get_tags\n",
      "ImportError: cannot import name 'get_tags' from 'sklearn.utils._tags' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_tags.py)\n",
      "]\n",
      "[autoreload of sklearn.model_selection failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\model_selection\\__init__.py\", line 8, in <module>\n",
      "    from ._classification_threshold import (\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\model_selection\\_classification_threshold.py\", line 21, in <module>\n",
      "    from ..metrics._scorer import (\n",
      "ImportError: cannot import name '_CurveScorer' from 'sklearn.metrics._scorer' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\metrics\\_scorer.py)\n",
      "]\n",
      "[autoreload of sklearn.neighbors._base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\neighbors\\_base.py\", line 25, in <module>\n",
      "    from ..utils import (\n",
      "ImportError: cannot import name 'get_tags' from 'sklearn.utils' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\__init__.py)\n",
      "]\n",
      "[autoreload of sklearn.neighbors._classification failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\neighbors\\_classification.py\", line 19, in <module>\n",
      "    from ..utils.arrayfuncs import _all_with_any_reduction_axis_1\n",
      "ImportError: cannot import name '_all_with_any_reduction_axis_1' from 'sklearn.utils.arrayfuncs' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\arrayfuncs.cp311-win_amd64.pyd)\n",
      "]\n",
      "[autoreload of sklearn.neighbors._graph failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 500, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 397, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 309, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: kneighbors_graph() requires a code object with 0 free vars, not 2946347565059\n",
      "]\n",
      "[autoreload of sklearn.neighbors._kde failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\neighbors\\_kde.py\", line 20, in <module>\n",
      "    from ..utils.validation import _check_sample_weight, check_is_fitted, validate_data\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\linear_model\\_base.py\", line 44, in <module>\n",
      "    from ..utils.validation import _check_sample_weight, check_is_fitted, validate_data\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._bayes failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\linear_model\\_bayes.py\", line 19, in <module>\n",
      "    from ..utils.validation import _check_sample_weight, validate_data\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._coordinate_descent failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\linear_model\\_coordinate_descent.py\", line 33, in <module>\n",
      "    from ..utils.validation import (\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._glm.glm failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\linear_model\\_glm\\glm.py\", line 25, in <module>\n",
      "    from ...utils.validation import _check_sample_weight, check_is_fitted, validate_data\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._huber failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\linear_model\\_huber.py\", line 14, in <module>\n",
      "    from ..utils.validation import _check_sample_weight, validate_data\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._least_angle failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\linear_model\\_least_angle.py\", line 38, in <module>\n",
      "    from ..utils.validation import validate_data\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.svm._base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\svm\\_base.py\", line 19, in <module>\n",
      "    from ..utils.validation import (\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.svm._classes failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\svm\\_classes.py\", line 12, in <module>\n",
      "    from ..utils.validation import _num_samples, validate_data\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._logistic failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\linear_model\\_logistic.py\", line 43, in <module>\n",
      "    from ..utils.validation import (\n",
      "ImportError: cannot import name '_check_method_params' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._omp failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\linear_model\\_omp.py\", line 26, in <module>\n",
      "    from ..utils.validation import validate_data\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n",
      "[autoreload of sklearn.linear_model._stochastic_gradient failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 276, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 475, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\linear_model\\_stochastic_gradient.py\", line 31, in <module>\n",
      "    from ..utils.validation import _check_sample_weight, check_is_fitted, validate_data\n",
      "ImportError: cannot import name 'validate_data' from 'sklearn.utils.validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py)\n",
      "]\n"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "cannot import name '_MissingValues' from 'sklearn.utils._param_validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[14], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mimblearn\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mover_sampling\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m SMOTE\n\u001b[0;32m      3\u001b[0m \u001b[38;5;66;03m# Instantiate SMOTE with a fixed random_state for reproducibility\u001b[39;00m\n\u001b[0;32m      4\u001b[0m smote \u001b[38;5;241m=\u001b[39m SMOTE(random_state\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m42\u001b[39m)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\imblearn\\__init__.py:52\u001b[0m\n\u001b[0;32m     48\u001b[0m     sys\u001b[38;5;241m.\u001b[39mstderr\u001b[38;5;241m.\u001b[39mwrite(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mPartial import of imblearn during the build process.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m     49\u001b[0m     \u001b[38;5;66;03m# We are not importing the rest of scikit-learn during the build\u001b[39;00m\n\u001b[0;32m     50\u001b[0m     \u001b[38;5;66;03m# process, as it may not be compiled yet\u001b[39;00m\n\u001b[0;32m     51\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m---> 52\u001b[0m     \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m     53\u001b[0m         combine,\n\u001b[0;32m     54\u001b[0m         ensemble,\n\u001b[0;32m     55\u001b[0m         exceptions,\n\u001b[0;32m     56\u001b[0m         metrics,\n\u001b[0;32m     57\u001b[0m         over_sampling,\n\u001b[0;32m     58\u001b[0m         pipeline,\n\u001b[0;32m     59\u001b[0m         tensorflow,\n\u001b[0;32m     60\u001b[0m         under_sampling,\n\u001b[0;32m     61\u001b[0m         utils,\n\u001b[0;32m     62\u001b[0m     )\n\u001b[0;32m     63\u001b[0m     \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_version\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m __version__\n\u001b[0;32m     64\u001b[0m     \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mbase\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m FunctionSampler\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\imblearn\\combine\\__init__.py:5\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;124;03m\"\"\"The :mod:`imblearn.combine` provides methods which combine\u001b[39;00m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;124;03mover-sampling and under-sampling.\u001b[39;00m\n\u001b[0;32m      3\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m----> 5\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_smote_enn\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m SMOTEENN\n\u001b[0;32m      6\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_smote_tomek\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m SMOTETomek\n\u001b[0;32m      8\u001b[0m __all__ \u001b[38;5;241m=\u001b[39m [\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mSMOTEENN\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mSMOTETomek\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\imblearn\\combine\\_smote_enn.py:12\u001b[0m\n\u001b[0;32m      9\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msklearn\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mbase\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m clone\n\u001b[0;32m     10\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msklearn\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutils\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m check_X_y\n\u001b[1;32m---> 12\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mbase\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m BaseSampler\n\u001b[0;32m     13\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mover_sampling\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m SMOTE\n\u001b[0;32m     14\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mover_sampling\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mbase\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m BaseOverSampler\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\imblearn\\base.py:21\u001b[0m\n\u001b[0;32m     18\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msklearn\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutils\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmulticlass\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m check_classification_targets\n\u001b[0;32m     20\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutils\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m check_sampling_strategy, check_target_type\n\u001b[1;32m---> 21\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutils\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_param_validation\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m validate_parameter_constraints\n\u001b[0;32m     22\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutils\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_validation\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ArraysTransformer\n\u001b[0;32m     25\u001b[0m \u001b[38;5;28;01mclass\u001b[39;00m \u001b[38;5;21;01mSamplerMixin\u001b[39;00m(BaseEstimator, metaclass\u001b[38;5;241m=\u001b[39mABCMeta):\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\imblearn\\utils\\_param_validation.py:908\u001b[0m\n\u001b[0;32m    906\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msklearn\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutils\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_param_validation\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m generate_valid_param  \u001b[38;5;66;03m# noqa\u001b[39;00m\n\u001b[0;32m    907\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msklearn\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutils\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_param_validation\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m validate_parameter_constraints  \u001b[38;5;66;03m# noqa\u001b[39;00m\n\u001b[1;32m--> 908\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01msklearn\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutils\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_param_validation\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (\n\u001b[0;32m    909\u001b[0m     HasMethods,\n\u001b[0;32m    910\u001b[0m     Hidden,\n\u001b[0;32m    911\u001b[0m     Interval,\n\u001b[0;32m    912\u001b[0m     Options,\n\u001b[0;32m    913\u001b[0m     StrOptions,\n\u001b[0;32m    914\u001b[0m     _ArrayLikes,\n\u001b[0;32m    915\u001b[0m     _Booleans,\n\u001b[0;32m    916\u001b[0m     _Callables,\n\u001b[0;32m    917\u001b[0m     _CVObjects,\n\u001b[0;32m    918\u001b[0m     _InstancesOf,\n\u001b[0;32m    919\u001b[0m     _IterablesNotString,\n\u001b[0;32m    920\u001b[0m     _MissingValues,\n\u001b[0;32m    921\u001b[0m     _NoneConstraint,\n\u001b[0;32m    922\u001b[0m     _PandasNAConstraint,\n\u001b[0;32m    923\u001b[0m     _RandomStates,\n\u001b[0;32m    924\u001b[0m     _SparseMatrices,\n\u001b[0;32m    925\u001b[0m     _VerboseHelper,\n\u001b[0;32m    926\u001b[0m     make_constraint,\n\u001b[0;32m    927\u001b[0m     validate_params,\n\u001b[0;32m    928\u001b[0m )\n",
      "\u001b[1;31mImportError\u001b[0m: cannot import name '_MissingValues' from 'sklearn.utils._param_validation' (C:\\Users\\Max Tost\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py)"
     ]
    }
   ],
   "source": [
    "from imblearn.over_sampling import SMOTE\n",
    "\n",
    "# Instantiate SMOTE with a fixed random_state for reproducibility\n",
    "smote = SMOTE(random_state=42)\n",
    "\n",
    "# Apply SMOTE only on the training data\n",
    "X_train_res, y_train_res = smote.fit_resample(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: imbalanced-learn in c:\\users\\max tost\\anaconda3\\lib\\site-packages (0.10.1)\n",
      "Collecting imbalanced-learn\n",
      "  Obtaining dependency information for imbalanced-learn from https://files.pythonhosted.org/packages/9d/41/721fec82606242a2072ee909086ff918dfad7d0199a9dfd4928df9c72494/imbalanced_learn-0.13.0-py3-none-any.whl.metadata\n",
      "  Downloading imbalanced_learn-0.13.0-py3-none-any.whl.metadata (8.8 kB)\n",
      "Requirement already satisfied: numpy<3,>=1.24.3 in c:\\users\\max tost\\anaconda3\\lib\\site-packages (from imbalanced-learn) (1.26.4)\n",
      "Requirement already satisfied: scipy<2,>=1.10.1 in c:\\users\\max tost\\anaconda3\\lib\\site-packages (from imbalanced-learn) (1.11.1)\n",
      "Collecting scikit-learn<2,>=1.3.2 (from imbalanced-learn)\n",
      "  Obtaining dependency information for scikit-learn<2,>=1.3.2 from https://files.pythonhosted.org/packages/a1/a6/c5b78606743a1f28eae8f11973de6613a5ee87366796583fb74c67d54939/scikit_learn-1.6.1-cp311-cp311-win_amd64.whl.metadata\n",
      "  Downloading scikit_learn-1.6.1-cp311-cp311-win_amd64.whl.metadata (15 kB)\n",
      "Collecting sklearn-compat<1,>=0.1 (from imbalanced-learn)\n",
      "  Obtaining dependency information for sklearn-compat<1,>=0.1 from https://files.pythonhosted.org/packages/f0/a8/ad69cf130fbd017660cdd64abbef3f28135d9e2e15fe3002e03c5be0ca38/sklearn_compat-0.1.3-py3-none-any.whl.metadata\n",
      "  Downloading sklearn_compat-0.1.3-py3-none-any.whl.metadata (18 kB)\n",
      "Requirement already satisfied: joblib<2,>=1.1.1 in c:\\users\\max tost\\anaconda3\\lib\\site-packages (from imbalanced-learn) (1.2.0)\n",
      "Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\\users\\max tost\\anaconda3\\lib\\site-packages (from imbalanced-learn) (2.2.0)\n",
      "Collecting threadpoolctl<4,>=2.0.0 (from imbalanced-learn)\n",
      "  Obtaining dependency information for threadpoolctl<4,>=2.0.0 from https://files.pythonhosted.org/packages/4b/2c/ffbf7a134b9ab11a67b0cf0726453cedd9c5043a4fe7a35d1cefa9a1bcfb/threadpoolctl-3.5.0-py3-none-any.whl.metadata\n",
      "  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)\n",
      "Downloading imbalanced_learn-0.13.0-py3-none-any.whl (238 kB)\n",
      "   ---------------------------------------- 0.0/238.4 kB ? eta -:--:--\n",
      "   --------------------------- ------------ 163.8/238.4 kB 4.8 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 238.4/238.4 kB 3.6 MB/s eta 0:00:00\n",
      "Downloading scikit_learn-1.6.1-cp311-cp311-win_amd64.whl (11.1 MB)\n",
      "   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--\n",
      "    --------------------------------------- 0.2/11.1 MB 5.3 MB/s eta 0:00:03\n",
      "   - -------------------------------------- 0.4/11.1 MB 3.8 MB/s eta 0:00:03\n",
      "   -- ------------------------------------- 0.6/11.1 MB 3.9 MB/s eta 0:00:03\n",
      "   -- ------------------------------------- 0.7/11.1 MB 4.3 MB/s eta 0:00:03\n",
      "   --- ------------------------------------ 1.0/11.1 MB 4.4 MB/s eta 0:00:03\n",
      "   ---- ----------------------------------- 1.1/11.1 MB 4.2 MB/s eta 0:00:03\n",
      "   ----- ---------------------------------- 1.4/11.1 MB 4.3 MB/s eta 0:00:03\n",
      "   ----- ---------------------------------- 1.6/11.1 MB 4.5 MB/s eta 0:00:03\n",
      "   ------ --------------------------------- 1.8/11.1 MB 4.3 MB/s eta 0:00:03\n",
      "   ------- -------------------------------- 2.1/11.1 MB 4.5 MB/s eta 0:00:03\n",
      "   ------- -------------------------------- 2.2/11.1 MB 4.4 MB/s eta 0:00:03\n",
      "   -------- ------------------------------- 2.5/11.1 MB 4.6 MB/s eta 0:00:02\n",
      "   --------- ------------------------------ 2.7/11.1 MB 4.5 MB/s eta 0:00:02\n",
      "   ---------- ----------------------------- 2.9/11.1 MB 4.6 MB/s eta 0:00:02\n",
      "   ----------- ---------------------------- 3.1/11.1 MB 4.6 MB/s eta 0:00:02\n",
      "   ----------- ---------------------------- 3.3/11.1 MB 4.7 MB/s eta 0:00:02\n",
      "   ------------ --------------------------- 3.5/11.1 MB 4.6 MB/s eta 0:00:02\n",
      "   ------------ --------------------------- 3.6/11.1 MB 4.5 MB/s eta 0:00:02\n",
      "   ------------- -------------------------- 3.8/11.1 MB 4.5 MB/s eta 0:00:02\n",
      "   -------------- ------------------------- 4.1/11.1 MB 4.6 MB/s eta 0:00:02\n",
      "   --------------- ------------------------ 4.3/11.1 MB 4.6 MB/s eta 0:00:02\n",
      "   --------------- ------------------------ 4.4/11.1 MB 4.5 MB/s eta 0:00:02\n",
      "   ---------------- ----------------------- 4.6/11.1 MB 4.5 MB/s eta 0:00:02\n",
      "   ----------------- ---------------------- 4.8/11.1 MB 4.5 MB/s eta 0:00:02\n",
      "   ----------------- ---------------------- 4.9/11.1 MB 4.5 MB/s eta 0:00:02\n",
      "   ------------------ --------------------- 5.1/11.1 MB 4.5 MB/s eta 0:00:02\n",
      "   ------------------ --------------------- 5.3/11.1 MB 4.4 MB/s eta 0:00:02\n",
      "   ------------------- -------------------- 5.4/11.1 MB 4.4 MB/s eta 0:00:02\n",
      "   -------------------- ------------------- 5.6/11.1 MB 4.4 MB/s eta 0:00:02\n",
      "   -------------------- ------------------- 5.8/11.1 MB 4.4 MB/s eta 0:00:02\n",
      "   --------------------- ------------------ 6.1/11.1 MB 4.4 MB/s eta 0:00:02\n",
      "   ---------------------- ----------------- 6.2/11.1 MB 4.3 MB/s eta 0:00:02\n",
      "   ---------------------- ----------------- 6.4/11.1 MB 4.3 MB/s eta 0:00:02\n",
      "   ----------------------- ---------------- 6.5/11.1 MB 4.3 MB/s eta 0:00:02\n",
      "   ----------------------- ---------------- 6.7/11.1 MB 4.2 MB/s eta 0:00:02\n",
      "   ------------------------ --------------- 6.8/11.1 MB 4.2 MB/s eta 0:00:02\n",
      "   ------------------------- -------------- 7.0/11.1 MB 4.2 MB/s eta 0:00:01\n",
      "   ------------------------- -------------- 7.2/11.1 MB 4.2 MB/s eta 0:00:01\n",
      "   -------------------------- ------------- 7.3/11.1 MB 4.2 MB/s eta 0:00:01\n",
      "   --------------------------- ------------ 7.6/11.1 MB 4.2 MB/s eta 0:00:01\n",
      "   ---------------------------- ----------- 7.9/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ----------------------------- ---------- 8.1/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ----------------------------- ---------- 8.3/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ------------------------------ --------- 8.5/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ------------------------------- -------- 8.7/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ------------------------------- -------- 8.9/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   -------------------------------- ------- 9.0/11.1 MB 4.2 MB/s eta 0:00:01\n",
      "   -------------------------------- ------- 9.1/11.1 MB 4.2 MB/s eta 0:00:01\n",
      "   --------------------------------- ------ 9.3/11.1 MB 4.2 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 9.6/11.1 MB 4.2 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 9.7/11.1 MB 4.2 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 10.0/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 10.3/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ------------------------------------- -- 10.4/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 10.6/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 10.8/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ---------------------------------------  11.1/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ---------------------------------------  11.1/11.1 MB 4.3 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 11.1/11.1 MB 4.2 MB/s eta 0:00:00\n",
      "Downloading sklearn_compat-0.1.3-py3-none-any.whl (18 kB)\n",
      "Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)\n",
      "Installing collected packages: threadpoolctl, scikit-learn, sklearn-compat, imbalanced-learn\n",
      "  Attempting uninstall: threadpoolctl\n",
      "    Found existing installation: threadpoolctl 2.2.0\n",
      "    Uninstalling threadpoolctl-2.2.0:\n",
      "      Successfully uninstalled threadpoolctl-2.2.0\n",
      "  Attempting uninstall: scikit-learn\n",
      "    Found existing installation: scikit-learn 1.3.0\n",
      "    Uninstalling scikit-learn-1.3.0:\n",
      "      Successfully uninstalled scikit-learn-1.3.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Could not install packages due to an OSError: [WinError 5] Zugriff verweigert: 'C:\\\\Users\\\\Max Tost\\\\anaconda3\\\\Lib\\\\site-packages\\\\~klearn\\\\datasets\\\\_svmlight_format_fast.cp311-win_amd64.pyd'\n",
      "Consider using the `--user` option or check the permissions.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade imbalanced-learn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
